/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppDeveloperRouteImport } from './routes/_app.developer'
import { Route as AppEvidenceRouteImport } from './routes/_app.evidence'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppMcpServersRouteImport } from './routes/_app.mcp-servers'
import { Route as AppMonitoringRouteImport } from './routes/_app.monitoring'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPoliciesRouteImport } from './routes/_app.policies'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app.settings.organization'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app.settings.preferences'
import { Route as AppSettingsProfileRouteImport } from './routes/_app.settings.profile'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppTeamIndexRouteImport } from './routes/_app.team.index'
import { Route as AppTeamGroupsRouteImport } from './routes/_app.team.groups'
import { Route as AppTeamMembersRouteImport } from './routes/_app.team.members'
import { Route as AppTeamRolesRouteImport } from './routes/_app.team.roles'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpServersRoute = AppMcpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppTeamGroupsRoute = AppTeamGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppTeamMembersRoute = AppTeamMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppTeamRolesRoute = AppTeamRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agents': typeof AppAgentsRoute
  '/approvals': typeof AppApprovalsRoute
  '/developer': typeof AppDeveloperRoute
  '/evidence': typeof AppEvidenceRoute
  '/integrations': typeof AppIntegrationsRoute
  '/mcp-servers': typeof AppMcpServersRoute
  '/monitoring': typeof AppMonitoringRoute
  '/notifications': typeof AppNotificationsRoute
  '/policies': typeof AppPoliciesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/team': typeof AppTeamRouteWithChildren
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/team/groups': typeof AppTeamGroupsRoute
  '/team/members': typeof AppTeamMembersRoute
  '/team/roles': typeof AppTeamRolesRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/team/': typeof AppTeamIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/agents': typeof AppAgentsRoute
  '/approvals': typeof AppApprovalsRoute
  '/developer': typeof AppDeveloperRoute
  '/evidence': typeof AppEvidenceRoute
  '/integrations': typeof AppIntegrationsRoute
  '/mcp-servers': typeof AppMcpServersRoute
  '/monitoring': typeof AppMonitoringRoute
  '/notifications': typeof AppNotificationsRoute
  '/policies': typeof AppPoliciesRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/team/groups': typeof AppTeamGroupsRoute
  '/team/members': typeof AppTeamMembersRoute
  '/team/roles': typeof AppTeamRolesRoute
  '/settings': typeof AppSettingsIndexRoute
  '/team': typeof AppTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/developer': typeof AppDeveloperRoute
  '/_app/evidence': typeof AppEvidenceRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/mcp-servers': typeof AppMcpServersRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/policies': typeof AppPoliciesRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/team': typeof AppTeamRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/team/groups': typeof AppTeamGroupsRoute
  '/_app/team/members': typeof AppTeamMembersRoute
  '/_app/team/roles': typeof AppTeamRolesRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/agents'
    | '/approvals'
    | '/developer'
    | '/evidence'
    | '/integrations'
    | '/mcp-servers'
    | '/monitoring'
    | '/notifications'
    | '/policies'
    | '/settings'
    | '/team'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/team/groups'
    | '/team/members'
    | '/team/roles'
    | '/settings/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/agents'
    | '/approvals'
    | '/developer'
    | '/evidence'
    | '/integrations'
    | '/mcp-servers'
    | '/monitoring'
    | '/notifications'
    | '/policies'
    | '/'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/team/groups'
    | '/team/members'
    | '/team/roles'
    | '/settings'
    | '/team'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/agents'
    | '/_app/approvals'
    | '/_app/developer'
    | '/_app/evidence'
    | '/_app/integrations'
    | '/_app/mcp-servers'
    | '/_app/monitoring'
    | '/_app/notifications'
    | '/_app/policies'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/billing'
    | '/_app/settings/organization'
    | '/_app/settings/preferences'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/team/groups'
    | '/_app/team/members'
    | '/_app/team/roles'
    | '/_app/settings/'
    | '/_app/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence': {
      id: '/_app/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp-servers': {
      id: '/_app/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/mcp-servers'
      preLoaderRoute: typeof AppMcpServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/team/groups': {
      id: '/_app/team/groups'
      path: '/groups'
      fullPath: '/team/groups'
      preLoaderRoute: typeof AppTeamGroupsRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/team/members': {
      id: '/_app/team/members'
      path: '/members'
      fullPath: '/team/members'
      preLoaderRoute: typeof AppTeamMembersRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/team/roles': {
      id: '/_app/team/roles'
      path: '/roles'
      fullPath: '/team/roles'
      preLoaderRoute: typeof AppTeamRolesRouteImport
      parentRoute: typeof AppTeamRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTeamRouteChildren {
  AppTeamGroupsRoute: typeof AppTeamGroupsRoute
  AppTeamMembersRoute: typeof AppTeamMembersRoute
  AppTeamRolesRoute: typeof AppTeamRolesRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamGroupsRoute: AppTeamGroupsRoute,
  AppTeamMembersRoute: AppTeamMembersRoute,
  AppTeamRolesRoute: AppTeamRolesRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppMcpServersRoute: typeof AppMcpServersRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTeamRoute: typeof AppTeamRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppDeveloperRoute: AppDeveloperRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppMcpServersRoute: AppMcpServersRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTeamRoute: AppTeamRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
